# Generated by Django 4.2 on 2023-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('book_pdf', models.FileField(upload_to='book-pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='podcast/')),
                ('title', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
            ],
        ),
    ]
