# Generated by Django 4.2 on 2023-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapp', '0006_settings_google_settings_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
