# Generated by Django 4.2 on 2023-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapp', '0007_alter_podcast_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
